// Generated by gencpp from file kalman_filter/Vector3Stamped.msg
// DO NOT EDIT!


#ifndef KALMAN_FILTER_MESSAGE_VECTOR3STAMPED_H
#define KALMAN_FILTER_MESSAGE_VECTOR3STAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kalman_filter
{
template <class ContainerAllocator>
struct Vector3Stamped_
{
  typedef Vector3Stamped_<ContainerAllocator> Type;

  Vector3Stamped_()
    : time(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Vector3Stamped_(const ContainerAllocator& _alloc)
    : time(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::kalman_filter::Vector3Stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kalman_filter::Vector3Stamped_<ContainerAllocator> const> ConstPtr;

}; // struct Vector3Stamped_

typedef ::kalman_filter::Vector3Stamped_<std::allocator<void> > Vector3Stamped;

typedef boost::shared_ptr< ::kalman_filter::Vector3Stamped > Vector3StampedPtr;
typedef boost::shared_ptr< ::kalman_filter::Vector3Stamped const> Vector3StampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kalman_filter::Vector3Stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kalman_filter::Vector3Stamped_<ContainerAllocator1> & lhs, const ::kalman_filter::Vector3Stamped_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kalman_filter::Vector3Stamped_<ContainerAllocator1> & lhs, const ::kalman_filter::Vector3Stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kalman_filter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman_filter::Vector3Stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kalman_filter::Vector3Stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman_filter::Vector3Stamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ed4dcb6382e6a419737c7a7d2a6e517";
  }

  static const char* value(const ::kalman_filter::Vector3Stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ed4dcb6382e6a41ULL;
  static const uint64_t static_value2 = 0x9737c7a7d2a6e517ULL;
};

template<class ContainerAllocator>
struct DataType< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kalman_filter/Vector3Stamped";
  }

  static const char* value(const ::kalman_filter::Vector3Stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::kalman_filter::Vector3Stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector3Stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kalman_filter::Vector3Stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kalman_filter::Vector3Stamped_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KALMAN_FILTER_MESSAGE_VECTOR3STAMPED_H
