(cl:in-package udp_pkg-msg)
(cl:export '(FRAME_ID-VAL
          FRAME_ID
          STAMP-VAL
          STAMP
          X_POS-VAL
          X_POS
          Y_POS-VAL
          Y_POS
          Z_POS-VAL
          Z_POS
          X_ORI-VAL
          X_ORI
          Y_ORI-VAL
          Y_ORI
          Z_ORI-VAL
          Z_ORI
          W_ORI-VAL
          W_ORI
          X_VEL-VAL
          X_VEL
          Y_VEL-VAL
          Y_VEL
          Z_VEL-VAL
          Z_VEL
          X_ACC-VAL
          X_ACC
          Y_ACC-VAL
          Y_ACC
          Z_ACC-VAL
          Z_ACC
))